# Generated by Django 2.1.7 on 2019-03-01 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_no', models.CharField(max_length=8)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('CellPhone_No', models.CharField(max_length=13)),
            ],
        ),
        migrations.AddField(
            model_name='login',
            name='Student_No',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimetableGen.StudentsRegister'),
        ),
    ]
