# Generated by Django 2.1.7 on 2019-03-01 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimetableGen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsregister',
            old_name='Student_no',
            new_name='Student_No',
        ),
    ]
