# Generated by Django 2.1.7 on 2019-03-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimetableGen', '0002_auto_20190301_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsregister',
            name='Email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentsregister',
            name='Student_No',
            field=models.IntegerField(max_length=13),
        ),
    ]
