# Generated by Django 2.1.7 on 2019-03-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimetableGen', '0003_auto_20190301_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsregister',
            name='Student_No',
            field=models.IntegerField(),
        ),
    ]
