image: python:latest

stages:
    - build
    - test
    - run
    
build:
    stage: build
    script:
        - python -V
        - echo "Building"
        - mkdir build
        - touch build/info.txt
    artifacts:
        paths:
            - build/
test:
  stage: test
  script:
    - echo "testing"
    - test -f "build/info.txt"
   # - pip install coverage
    - python manage.py test
    #- coverage run manage.py
    #- coverage report -m
    - pip install tox flake8  
    


pep8:
  stage: test
  image: python:2.7
  script:
    - pip install tox
    - tox -e pep8
 # tags:
  #  - python27

unittest-py37:
  stage: test
  image: python:3.7
  script:
    - pip install tox
    - tox -e py37
  #tags:
   # - python27

unittest-py27:
  stage: test
  image: python:2.7
  script:
    - pip install tox
    - tox -e py27
 


sphnix:
  stage: test
  image: python:3.7
  script:
    - pip install tox
    - tox -e docs
 # tags:
  #  - python27


  
pages:
  script:
    - pip install sphinx sphinx-rtd-theme
  artifacts:
    paths:
        - build/
  only:
    - Tshepang
run:
  script:
    - python manage.py bdist_wheel
    - pip install sphinx sphinx-rtd-theme
  # an alternative approach is to install and run:
  artifacts:
    paths:
        - build/