image: python:latest

stages:
    - build
    - test
    - run
    
build:
    stage: build
    script:
        - python -V
        - echo "Building"
        - mkdir build
        - touch build/info.txt
    artifacts:
        paths:
            - build/
test:
  stage: test
  script:
    - echo "testing"
    - test -f "build/info.txt"
    - pip install coverage
    - python manage.py test
    - coverage run manage.py
    - coverage report -m
    


pep8:
  stage: test
  image: python:3.7
  script:
    - pip install tox
    - tox -e pep8
 # tags:
  #  - python27

unittest-py37:
  stage: test
  image: python:3.7
  script:
    - pip install tox
    - tox -e py37
  #tags:
   # - python27



sphnix:
  stage: test
  image: python:3.7
  script:
    - pip install tox
    - tox -e docs
 # tags:
  #  - python27

#build:
 # stage: build
  #tags:
   # - shell
 # script:
  #  - docker build -t skeleton .
 # only:
  #  - master

#deploy:
 # stage: deploy
  #tags:
   # - shell
  #script:
  #  - scripts/deploy.sh
   # - export
 # only:
  #  - sfiso

  
pages:
  script:
    - pip install sphinx sphinx-rtd-theme
  artifacts:
    paths:
        - build/
  only:
    - sfiso
run:
  script:
    - python manage.py bdist_wheel
  # an alternative approach is to install and run:
  artifacts:
    paths:
        - build/
    

#variables:
  #PIP_CACHE_DIR: "$loggedin/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
#cache:
 # paths:
  #  - .cache/pip
   # - venv/

#before_script:
 # - python -V               # Print out python version for debugging
  #- pip install virtualenv
 # - pip install coverage
  #- virtualenv venv
  #- source venv/bin/activate


  #- bash <(curl -s https://codecov.io/bash)>
  
  
 # - pip install tox flake8  # you can also use tox
 # - tox -e py36,flake8


     


