# Generated by Django 2.1.7 on 2019-05-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='pdf',
            field=models.FileField(null=True, upload_to='announcements/pdfs/'),
        ),
    ]
